### ISSUE TITLE
Sites with relative  urls end up rewritten as `example.com`

### ISSUE THREAD

**Issue by Ramblurr** [ArchiveBox/readability-extractor#2]
This line https://github.com/ArchiveBox/readability-extractor/blob/0098f142b0a015c8c90766d3b74d9eb6fb7b7e6a/readability-extractor#L13-L15 causes sites that use relative urls like `<img src="/image.png" />` to be rewritten as `<img src="https://www.example.com/image.png" />`

This tool really needs to be passed the original page url in order to properly rewrite relative urls.

**Comment by pirate** [comment]
Good point, thanks for reporting. I avoided doing it earlier because it means handling an extra param that might contain shellcode injection vectors and it didn't look like it was necessary. However given that it's causing problems, I'll change it to pass the original URL correctly.

- fix for `readability-extractor` to handle original URL arg: https://github.com/ArchiveBox/readability-extractor/commit/37a924be66a70f67c0978855eab76ed0442e795e
- fix for `archivebox` to pass original URL arg to `readability-extractor`: https://github.com/ArchiveBox/ArchiveBox/commit/eb4d3bca9de04ac371d8b66f0616a4d98ef86e44

Should be out with the next release v0.6.3: https://github.com/ArchiveBox/ArchiveBox/pull/721 (subscribe here for a notification when it's out)
